spring.application.name=SmartInterviewSimulator
# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG (MySQL)

# ===============================

spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL:${MYSQL_URL:jdbc:mysql://b5x1cctqu6labymwmgol-mysql.services.clever-cloud.com:22042/b5x1cctqu6labymwmgol?useSSL=true&allowPublicKeyRetrieval=true}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:${MYSQL_USER:uvuscmenvvs3crap}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:${MYSQL_PASSWORD:Rm9O2U6DydFoVtirppL}}}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================

jwt.expiration=3600000



groq.api.key=${GROQ_API_KEY:YOUR_GROQ_API_KEY}
groq.url=https://api.groq.com/openai/v1/chat/completions
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}

# ===============================
# OPENAI / GEMINI CONFIG
# ===============================
gemini.api.key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
# ===============================
# LOGGING (OPTIONAL)
# ===============================
logging.level.org.springframework=INFO
logging.level.com.interview.simulator=DEBUG
